version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    volumes:
      - node_modules:/app/node_modules
      - bundle:/bundle
      - .:/app
    env_file: ./docker/.env
    ports:
      - "80:3001"
      - "3035:3035"

volumes:
  node_modules:
    driver: local
  bundle:
    driver: local
