version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    volumes:
      - node_modules:/app/node_modules
      - bundle:/usr/local/bundle
      - .:/app
    env_file: ./docker/.env
    ports:
      - "3000:3000"

volumes:
  node_modules:
    driver: local
  bundle:
    driver: local
